version: '3'
services:
  db1:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser1
      POSTGRES_PASSWORD: dbpassword1
      POSTGRES_DB: database1
    volumes:
      - ./data/db1:/var/lib/postgresql/data
    ports:
      - "5431:5432"
