version: '3'
services:
  db1:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser1
      POSTGRES_PASSWORD: dbpassword1
      POSTGRES_DB: database1
    volumes:
      - ./data/db1:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  db2:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser2
      POSTGRES_PASSWORD: dbpassword2
      POSTGRES_DB: database2
    volumes:
      - ./data/db2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db3:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser3
      POSTGRES_PASSWORD: dbpassword3
      POSTGRES_DB: database3
    volumes:
      - ./data/db3:/var/lib/postgresql/data
    ports:
      - "5433:5432"
